"""empty message

Revision ID: d75d6af4ccfc
Revises: fcecb3e58853
Create Date: 2022-09-20 13:31:44.064214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75d6af4ccfc'
down_revision = 'fcecb3e58853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_name_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_name_key', 'profile', ['name'])
    # ### end Alembic commands ###
