"""empty message

Revision ID: b23e3947ae9b
Revises: d44477b6084a
Create Date: 2022-08-10 15:27:51.270259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23e3947ae9b'
down_revision = 'd44477b6084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('new_profile', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'new_profile')
    # ### end Alembic commands ###
