"""empty message

Revision ID: fcecb3e58853
Revises: 234dec7af82c
Create Date: 2022-08-11 16:22:24.333881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcecb3e58853'
down_revision = '234dec7af82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('avatar_url', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'avatar_url')
    # ### end Alembic commands ###
