"""empty message

Revision ID: 58631a05afb4
Revises: ab9e4b41583b
Create Date: 2023-02-05 13:04:04.260639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58631a05afb4'
down_revision = 'ab9e4b41583b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_favorite', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_favorite', 'id')
    # ### end Alembic commands ###
