"""empty message

Revision ID: cf650f3e813e
Revises: ae1ccdc2f266
Create Date: 2023-02-02 21:47:48.157724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf650f3e813e'
down_revision = 'ae1ccdc2f266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('title', sa.String(length=300), nullable=False))
    op.add_column('favorite', sa.Column('url', sa.String(length=300), nullable=False))
    op.add_column('favorite', sa.Column('image', sa.String(length=300), nullable=False))
    op.add_column('favorite', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('favorite', sa.Column('description', sa.String(), nullable=False))
    op.add_column('favorite', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'created_at')
    op.drop_column('favorite', 'description')
    op.drop_column('favorite', 'genres')
    op.drop_column('favorite', 'image')
    op.drop_column('favorite', 'url')
    op.drop_column('favorite', 'title')
    # ### end Alembic commands ###
