"""empty message

Revision ID: ae1ccdc2f266
Revises: d75d6af4ccfc
Create Date: 2023-02-02 21:34:20.113755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1ccdc2f266'
down_revision = 'd75d6af4ccfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('favorite_user_id_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_show_id_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'profile', ['profile_id'], ['id'])
    op.drop_column('favorite', 'show_id')
    op.drop_column('favorite', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('favorite', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_show_id_fkey', 'favorite', 'shows', ['show_id'], ['id'])
    op.create_foreign_key('favorite_user_id_fkey', 'favorite', 'users', ['user_id'], ['id'])
    op.drop_column('favorite', 'profile_id')
    # ### end Alembic commands ###
