"""empty message

Revision ID: ec200ee55dec
Revises: dd5f4887a79b
Create Date: 2023-02-20 04:09:25.301352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec200ee55dec'
down_revision = 'dd5f4887a79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_favorite', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_favorite', 'favorite_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('profile_favorite', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_favorite', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('profile_favorite', 'favorite_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_favorite', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
