"""empty message

Revision ID: f602058ef524
Revises: ed7adf343e58
Create Date: 2023-02-05 01:18:37.210918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f602058ef524'
down_revision = 'ed7adf343e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_profile_id_fkey', 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favorite_profile_id_fkey', 'favorite', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###
