"""empty message

Revision ID: b7ea2698d373
Revises: bf96bdc5d94a
Create Date: 2023-02-06 15:09:03.562178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ea2698d373'
down_revision = 'bf96bdc5d94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_profile_id_fkey', 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favorite_profile_id_fkey', 'favorite', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###
