"""empty message

Revision ID: 1f170e1c80c8
Revises: 90a255876fbb
Create Date: 2023-03-07 19:15:51.265589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f170e1c80c8'
down_revision = '90a255876fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_favorite', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_favorite', 'favorite_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('profile_favorite', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_favorite', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('profile_favorite', 'favorite_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_favorite', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
